packaging_format = 2

id = "243game"
name = "243"
description.en = "2048 game clone"
description.fr = "Clone du jeu 2048"

version = "1.0~ynh6"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
demo = "https://hgentry.github.io/81/"
code = "https://github.com/hgentry/81"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/243"

    [install.init_main_permission]
    help.en = "If enabled, 243 will be accessible by people who doesn’t have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, 243 sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/hgentry/81/archive/gh-pages.tar.gz"
        sha256 = "c7d2052999ae4d2e0c5fd5ff1dd6bfb794b7f2bc5caa63f4fbc5e195509c00b9"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
